/**
 * INTERACTIVE ASTROPHYSICAL BLACK HOLE LABORATORY
 * Powered by Three.js & General Relativity Approximations
 */

// ==========================================================================
// 1. PHYSICAL CONSTANTS
// ==========================================================================
const G = 6.67430e-11;            // Gravitational Constant (m^3 kg^-1 s^-2)
const C = 299792458;              // Speed of Light (m/s)
const SOLAR_MASS = 1.98847e30;    // 1 Solar Mass (kg)
const BOLTZMANN = 1.380649e-23;   // Boltzmann Constant (J/K)

// ==========================================================================
// 2. SIMULATION STATE
// ==========================================================================
const state = {
  mass: 10.0,             // Solar Masses (M☉)
  spin: 0.720,            // Kerr dimensionless spin parameter a* (0 to 0.998)
  accretionRate: 0.35,    // 0.0 to 1.0 dimensionless
  viewingAngle: 65,       // Degrees
  simSpeed: 1.0,          // Time multiplier
  jetsEnabled: true,
  ergosphereEnabled: false,
  activeFilter: 'NORMAL',
  cameraPreset: 'orbit',
  
  // Transition interpolators
  filterTransitionProgress: 1.0,
  targetFilter: 'NORMAL',
  previousFilter: 'NORMAL'
};

// Mode Color & Visualization Maps
const FILTER_MODES = {
  NORMAL: {
    title: 'NORMAL MODE',
    desc: 'Relativistic visual view: photon lensing ring, Doppler boosting asymmetry, turbulent inner plasma.',
    innerColor: [1.0, 0.9, 0.7],
    outerColor: [0.9, 0.3, 0.05]
  },
  XRAY: {
    title: 'X-RAY EMISSION MODE',
    desc: 'Simulated high-energy bremsstrahlung & synchrotron radiation from ultra-hot inner accretion plasma.',
    innerColor: [0.3, 0.8, 1.0],
    outerColor: [0.05, 0.1, 0.6]
  },
  TEMPERATURE: {
    title: 'TEMPERATURE MAP',
    desc: 'Thermal profile where T(r) ∝ r^(-3/4). Peak extreme temperatures occur near ISCO boundary.',
    innerColor: [1.0, 0.2, 0.8],
    outerColor: [0.2, 0.0, 0.6]
  },
  PRESSURE: {
    title: 'PLASMA PRESSURE MAP',
    desc: 'Plasma pressure profile derived via P ≈ n·k·T across accretion density gradient.',
    innerColor: [1.0, 0.1, 0.1],
    outerColor: [0.4, 0.1, 0.0]
  },
  DENSITY: {
    title: 'DENSITY PROFILE',
    desc: 'Volumetric particle number density visualization showing inwards spiral mass compaction.',
    innerColor: [0.2, 1.0, 0.4],
    outerColor: [0.0, 0.3, 0.1]
  },
  GRAVITY: {
    title: 'GRAVITATIONAL FIELD STRENGTH',
    desc: 'Gradient displaying relativistic acceleration g ≈ GM / r^2 reaching extreme values near horizon.',
    innerColor: [1.0, 1.0, 0.2],
    outerColor: [0.5, 0.2, 0.0]
  },
  VELOCITY: {
    title: 'ORBITAL VELOCITY GRADIENT',
    desc: 'Keplerian orbital velocity mapping v ≈ √(GM/r) approaching significant fractions of c.',
    innerColor: [0.1, 0.9, 1.0],
    outerColor: [0.0, 0.2, 0.5]
  },
  SPACETIME: {
    title: 'CONCEPTUAL SPACETIME CURVATURE',
    desc: '3D coordinate grid deformation mapping gravitational potential well around central mass.',
    innerColor: [0.8, 0.4, 1.0],
    outerColor: [0.1, 0.1, 0.3]
  },
  MAGNETIC: {
    title: 'ILLUSTRATIVE MAGNETIC FIELD',
    desc: 'Toroidal & poloidal field lines generated by spinning ionized plasma accreting into black hole.',
    innerColor: [1.0, 0.5, 0.0],
    outerColor: [0.2, 0.5, 1.0]
  },
  TIMEDILATION: {
    title: 'TIME DILATION GRADIENT',
    desc: 'Gravitational redshift & clock slowing derived from Schwarzschild metric dτ = dt √(1 - r_s/r).',
    innerColor: [0.0, 1.0, 0.8],
    outerColor: [0.0, 0.2, 0.3]
  }
};

// ==========================================================================
// 3. PHYSICS COMPUTATION FUNCTIONS
// ==========================================================================
function calculateSchwarzschildRadius(massMsolar) {
  const mKg = massMsolar * SOLAR_MASS;
  return (2 * G * mKg) / (C * C); // meters
}

// Innermost Stable Circular Orbit (ISCO) Kerr approximation
function calculateISCO(massMsolar, spin) {
  const rs = calculateSchwarzschildRadius(massMsolar);
  const rh = rs / 2; // Approximate Kerr horizon
  // Z1, Z2 Kerr factors approximation
  const Z1 = 1 + Math.pow(1 - spin * spin, 1/3) * (Math.pow(1 + spin, 1/3) + Math.pow(1 - spin, 1/3));
  const Z2 = Math.sqrt(3 * spin * spin + Z1 * Z1);
  const rms = rh * (3 + Z2 - Math.sqrt((3 - Z1) * (3 + Z1 + 2 * Z2)));
  return Math.max(rms, rh * 1.1);
}

function calculateOrbitalVelocity(massMsolar, radiusMeters) {
  const mKg = massMsolar * SOLAR_MASS;
  const v = Math.sqrt((G * mKg) / radiusMeters);
  return Math.min(v, C * 0.999); // Physical clamp below c
}

function calculateTemperature(massMsolar, radiusMeters, accretionRate) {
  const rs = calculateSchwarzschildRadius(massMsolar);
  const ratio = Math.max(radiusMeters / rs, 1.2);
  // Standard Shakura-Sunyaev disk temperature profile T(r) ∝ r^(-3/4)
  const baseT = 1.2e7 * Math.pow(10 / massMsolar, 0.25) * Math.pow(accretionRate, 0.25);
  return baseT * Math.pow(ratio, -0.75);
}

function calculateDensity(radiusMeters, accretionRate, massMsolar) {
  const rs = calculateSchwarzschildRadius(massMsolar);
  const rNorm = Math.max(radiusMeters / rs, 1.0);
  return (2.4e-6 * accretionRate) / Math.pow(rNorm, 1.5); // kg/m^3
}

function calculatePressure(density, temperature) {
  const n = density / (1.67e-27); // Proton number density approx
  return n * BOLTZMANN * temperature; // Pa
}

function calculateGravity(massMsolar, radiusMeters) {
  const mKg = massMsolar * SOLAR_MASS;
  return (G * mKg) / (radiusMeters * radiusMeters); // m/s^2
}

function calculateTimeDilation(massMsolar, radiusMeters) {
  const rs = calculateSchwarzschildRadius(massMsolar);
  if (radiusMeters <= rs) return 0.0;
  return Math.sqrt(1.0 - (rs / radiusMeters));
}

// Format numbers nicely into scientific notation
function formatSci(val, decimals = 2) {
  if (val === 0) return "0";
  const exp = Math.floor(Math.log10(Math.abs(val)));
  const mantissa = val / Math.pow(10, exp);
  if (Math.abs(exp) < 3) return val.toFixed(decimals);
  return `${mantissa.toFixed(decimals)} × 10¹³`.replace('10¹³', `10${getSuperscript(exp)}`);
}

function getSuperscript(num) {
  const supers = {'-': '⁻', '0': '⁰', '1': '¹', '2': '²', '3': '³', '4': '⁴', '5': '⁵', '6': '⁶', '7': '⁷', '8': '⁸', '9': '⁹'};
  return String(num).split('').map(c => supers[c] || c).join('');
}

// ==========================================================================
// 4. THREE.JS SCENE & INITIALIZATION
// ==========================================================================
let scene, camera, renderer, controls;
let eventHorizonMesh, photonRingMesh, lensingDiskMesh, ergosphereMesh;
let particleSystem, particlePositions, particleColors, particleData;
let jetSystem, jetPositions, jetColors;
let spacetimeGrid, magneticLinesGroup, starField;

const PARTICLE_COUNT = 16000;
const JET_PARTICLE_COUNT = 2500;
const SCALE_FACTOR = 1 / 1000; // Meters to visual units conversion base

function initThree() {
  const container = document.getElementById('canvas-container');

  // WebGL Fallback Check
  if (!window.WebGLRenderingContext) {
    document.getElementById('webgl-fallback').classList.remove('hidden');
    return false;
  }

  // Scene
  scene = new THREE.Scene();
  scene.background = new THREE.Color(0x030406);
  scene.fog = new THREE.FogExp2(0x030406, 0.002);

  // Camera
  camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 1000);
  camera.position.set(0, 18, 38);

  // Renderer
  renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false, powerPreference: "high-performance" });
  renderer.setSize(window.innerWidth, window.innerHeight);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.2;
  container.appendChild(renderer.domElement);

  // Controls
  controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.05;
  controls.maxDistance = 150;
  controls.minDistance = 4;

  // Build Object Subsystems
  createStarField();
  createBlackCore();
  createAccretionDisk();
  createGravitationalLensingMesh();
  createJets();
  createErgosphere();
  createSpacetimeGrid();
  createMagneticFieldLines();

  // Window Resize Event
  window.addEventListener('resize', onWindowResize);

  return true;
}

// ==========================================================================
// 5. MESH BUILDERS
// ==========================================================================

// Black Hole Core (Event Horizon)
function createBlackCore() {
  const geo = new THREE.SphereGeometry(1, 64, 64);
  const mat = new THREE.MeshBasicMaterial({
    color: 0x000000
  });
  eventHorizonMesh = new THREE.Mesh(geo, mat);
  scene.add(eventHorizonMesh);

  // Bright Photons Boundary Ring
  const ringGeo = new THREE.RingGeometry(1.02, 1.18, 128);
  const ringMat = new THREE.MeshBasicMaterial({
    color: 0xffffff,
    side: THREE.DoubleSide,
    transparent: true,
    opacity: 0.95,
    blending: THREE.AdditiveBlending
  });
  photonRingMesh = new THREE.Mesh(ringGeo, ringMat);
  photonRingMesh.rotation.x = Math.PI / 2;
  scene.add(photonRingMesh);
}

// Gravitational Lensing Secondary Warp Halo (Warped Disk Visual)
function createGravitationalLensingMesh() {
  const geo = new THREE.RingGeometry(1.2, 5.5, 96, 16);
  // Custom Vertex Warping Shader to simulate Einstein Light Bending over Horizon
  const mat = new THREE.ShaderMaterial({
    uniforms: {
      uTime: { value: 0 },
      uColorInner: { value: new THREE.Color(1.0, 0.9, 0.7) },
      uColorOuter: { value: new THREE.Color(0.9, 0.3, 0.05) },
      uOpacity: { value: 0.6 }
    },
    vertexShader: `
      varying vec2 vUv;
      varying float vDist;
      void main() {
        vUv = uv;
        vec3 pos = position;
        float r = length(pos.xy);
        // Vertical warp simulation for gravitational lensing arc
        pos.z += sin(r * 2.0) * 0.15 * (1.0 / (r - 0.9));
        vDist = r;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
      }
    `,
    fragmentShader: `
      uniform vec3 uColorInner;
      uniform vec3 uColorOuter;
      uniform float uOpacity;
      varying float vDist;
      void main() {
        float t = smoothstep(1.2, 5.5, vDist);
        vec3 col = mix(uColorInner, uColorOuter, t);
        float alpha = (1.0 - t) * uOpacity * smoothstep(1.2, 1.5, vDist);
        gl_FragColor = vec4(col, alpha);
      }
    `,
    transparent: true,
    side: THREE.DoubleSide,
    blending: THREE.AdditiveBlending,
    depthWrite: false
  });

  lensingDiskMesh = new THREE.Mesh(geo, mat);
  lensingDiskMesh.rotation.x = Math.PI / 2.3; // Angle offset for lensing effect
  scene.add(lensingDiskMesh);
}

// Primary Accretion Disk (16,000 Particle Swarm)
function createAccretionDisk() {
  const geo = new THREE.BufferGeometry();
  particlePositions = new Float32Array(PARTICLE_COUNT * 3);
  particleColors = new Float32Array(PARTICLE_COUNT * 3);
  particleData = [];

  const innerR = 2.2;
  const outerR = 12.0;

  for (let i = 0; i < PARTICLE_COUNT; i++) {
    const r = innerR + Math.pow(Math.random(), 2.2) * (outerR - innerR);
    const theta = Math.random() * Math.PI * 2;
    const yHeight = (Math.random() - 0.5) * 0.18 * (r / outerR); // Thin disk profile

    particlePositions[i * 3] = r * Math.cos(theta);
    particlePositions[i * 3 + 1] = yHeight;
    particlePositions[i * 3 + 2] = r * Math.sin(theta);

    particleColors[i * 3] = 1.0;
    particleColors[i * 3 + 1] = 0.5;
    particleColors[i * 3 + 2] = 0.2;

    particleData.push({
      radius: r,
      angle: theta,
      y: yHeight,
      speed: 0.8 / Math.sqrt(r), // Keplerian velocity curve
      turbulence: (Math.random() - 0.5) * 0.02
    });
  }

  geo.setAttribute('position', new THREE.BufferAttribute(particlePositions, 3));
  geo.setAttribute('color', new THREE.BufferAttribute(particleColors, 3));

  const mat = new THREE.PointsMaterial({
    size: 0.12,
    vertexColors: true,
    transparent: true,
    opacity: 0.85,
    blending: THREE.AdditiveBlending,
    depthWrite: false
  });

  particleSystem = new THREE.Points(geo, mat);
  scene.add(particleSystem);
}

// Relativistic Jets
function createJets() {
  const geo = new THREE.BufferGeometry();
  jetPositions = new Float32Array(JET_PARTICLE_COUNT * 3);
  jetColors = new Float32Array(JET_PARTICLE_COUNT * 3);

  for (let i = 0; i < JET_PARTICLE_COUNT; i++) {
    const dir = Math.random() > 0.5 ? 1 : -1;
    const h = Math.random() * 18;
    const r = (Math.random() * 0.1 + 0.02) * (1 + h * 0.2);
    const theta = Math.random() * Math.PI * 2;

    jetPositions[i * 3] = r * Math.cos(theta);
    jetPositions[i * 3 + 1] = h * dir;
    jetPositions[i * 3 + 2] = r * Math.sin(theta);

    jetColors[i * 3] = 0.3;
    jetColors[i * 3 + 1] = 0.7;
    jetColors[i * 3 + 2] = 1.0;
  }

  geo.setAttribute('position', new THREE.BufferAttribute(jetPositions, 3));
  geo.setAttribute('color', new THREE.BufferAttribute(jetColors, 3));

  const mat = new THREE.PointsMaterial({
    size: 0.16,
    vertexColors: true,
    transparent: true,
    opacity: 0.7,
    blending: THREE.AdditiveBlending,
    depthWrite: false
  });

  jetSystem = new THREE.Points(geo, mat);
  scene.add(jetSystem);
}

// Ergosphere (Oblate Spheroid)
function createErgosphere() {
  const geo = new THREE.SphereGeometry(1.4, 32, 32);
  geo.scale(1.5, 1.0, 1.5); // Oblate deformation due to spin
  const mat = new THREE.MeshBasicMaterial({
    color: 0x38bdf8,
    wireframe: true,
    transparent: true,
    opacity: 0.15
  });
  ergosphereMesh = new THREE.Mesh(geo, mat);
  ergosphereMesh.visible = false;
  scene.add(ergosphereMesh);
}

// Spacetime Curvature Coordinate Grid
function createSpacetimeGrid() {
  const size = 30;
  const divisions = 40;
  const geo = new THREE.PlaneGeometry(size, size, divisions, divisions);
  geo.rotateX(-Math.PI / 2);

  const pos = geo.attributes.position;
  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i);
    const z = pos.getZ(i);
    const r = Math.sqrt(x * x + z * z);
    const warp = -2.5 / (r + 0.8); // Gravitational well deformation
    pos.setY(i, warp);
  }
  geo.computeVertexNormals();

  const mat = new THREE.MeshBasicMaterial({
    color: 0x8b5cf6,
    wireframe: true,
    transparent: true,
    opacity: 0.25
  });

  spacetimeGrid = new THREE.Mesh(geo, mat);
  spacetimeGrid.position.y = -2;
  spacetimeGrid.visible = false;
  scene.add(spacetimeGrid);
}

// Illustrative Magnetic Field Lines
function createMagneticFieldLines() {
  magneticLinesGroup = new THREE.Group();
  const lineCount = 16;

  for (let i = 0; i < lineCount; i++) {
    const angle = (i / lineCount) * Math.PI * 2;
    const curve = new THREE.CubicBezierCurve3(
      new THREE.Vector3(0, 0.2, 0),
      new THREE.Vector3(Math.cos(angle) * 6, 8, Math.sin(angle) * 6),
      new THREE.Vector3(Math.cos(angle) * 12, -8, Math.sin(angle) * 12),
      new THREE.Vector3(0, -0.2, 0)
    );

    const points = curve.getPoints(50);
    const geo = new THREE.BufferGeometry().setFromPoints(points);
    const mat = new THREE.LineBasicMaterial({
      color: 0xf59e0b,
      transparent: true,
      opacity: 0.4
    });

    const line = new THREE.Line(geo, mat);
    magneticLinesGroup.add(line);
  }

  magneticLinesGroup.visible = false;
  scene.add(magneticLinesGroup);
}

// Multi-layered Starfield
function createStarField() {
  const count = 3000;
  const geo = new THREE.BufferGeometry();
  const pos = new Float32Array(count * 3);
  const colors = new Float32Array(count * 3);

  for (let i = 0; i < count; i++) {
    const r = 150 + Math.random() * 200;
    const theta = Math.random() * Math.PI * 2;
    const phi = Math.acos((Math.random() * 2) - 1);

    pos[i * 3] = r * Math.sin(phi) * Math.cos(theta);
    pos[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta);
    pos[i * 3 + 2] = r * Math.cos(phi);

    const brightness = 0.4 + Math.random() * 0.6;
    colors[i * 3] = brightness;
    colors[i * 3 + 1] = brightness * (0.8 + Math.random() * 0.2);
    colors[i * 3 + 2] = brightness;
  }

  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  geo.setAttribute('color', new THREE.BufferAttribute(colors, 3));

  const mat = new THREE.PointsMaterial({
    size: 1.2,
    vertexColors: true,
    transparent: true,
    opacity: 0.8
  });

  starField = new THREE.Points(geo, mat);
  scene.add(starField);
}

// ==========================================================================
// 6. ANIMATION & PHYSICAL UPDATES
// ==========================================================================
let clock = new THREE.Clock();

function animate() {
  requestAnimationFrame(animate);

  const delta = clock.getDelta() * state.simSpeed;
  const time = clock.getElapsedTime();

  // 1. Update Black Hole Physical Scales
  const rsMeters = calculateSchwarzschildRadius(state.mass);
  const visualRadius = Math.max(0.6, Math.log10(state.mass) * 0.8 + 0.6); // Scaled for visibility
  
  eventHorizonMesh.scale.setScalar(visualRadius);
  photonRingMesh.scale.setScalar(visualRadius * 1.35);

  // Ergosphere scale & visibility
  if (state.ergosphereEnabled && state.spin > 0.05) {
    ergosphereMesh.visible = true;
    const ergoX = visualRadius * (1 + Math.sqrt(1 - state.spin * state.spin * 0.5));
    ergosphereMesh.scale.set(ergoX * 1.2, visualRadius * 1.05, ergoX * 1.2);
    ergosphereMesh.rotation.y += delta * state.spin * 2.0;
  } else {
    ergosphereMesh.visible = false;
  }

  // 2. Animate Accretion Disk Particles with Relativistic Doppler Boosting
  const posAttr = particleSystem.geometry.attributes.position;
  const colAttr = particleSystem.geometry.attributes.color;
  const mode = FILTER_MODES[state.activeFilter];

  // Camera direction for Doppler effect calculation
  const camDir = camera.position.clone().normalize();

  for (let i = 0; i < PARTICLE_COUNT; i++) {
    const p = particleData[i];

    // Keplerian orbital rotation speed modulated by Spin & Mass
    const omega = (p.speed * (1 + state.spin * 0.4)) / Math.max(visualRadius, 0.5);
    p.angle += omega * delta;

    // Inward spiral motion
    p.radius -= delta * 0.08 * state.accretionRate;
    if (p.radius < visualRadius * 1.1) {
      p.radius = 12.0; // Reset to outer rim when falling crossing horizon
    }

    const currentR = p.radius;
    const x = currentR * Math.cos(p.angle);
    const z = currentR * Math.sin(p.angle);
    const y = p.y + Math.sin(time * 2 + p.angle * 3) * p.turbulence;

    posAttr.setXYZ(i, x, y, z);

    // Relativistic Doppler Boosting Asymmetry (Approaching vs Receding side)
    const velVec = new THREE.Vector3(-Math.sin(p.angle), 0, Math.cos(p.angle));
    const dopplerDot = velVec.dot(camDir);
    const dopplerFactor = 1.0 + dopplerDot * 0.45 * (visualRadius / currentR);

    // Color Interpolation based on active Filter mode
    const normR = (currentR - visualRadius) / (12.0 - visualRadius);
    const clampedR = Math.max(0, Math.min(1, normR));

    let rCol = THREE.MathUtils.lerp(mode.innerColor[0], mode.outerColor[0], clampedR) * dopplerFactor;
    let gCol = THREE.MathUtils.lerp(mode.innerColor[1], mode.outerColor[1], clampedR) * dopplerFactor;
    let bCol = THREE.MathUtils.lerp(mode.innerColor[2], mode.outerColor[2], clampedR) * dopplerFactor;

    colAttr.setXYZ(i, Math.min(1, rCol), Math.min(1, gCol), Math.min(1, bCol));
  }

  posAttr.needsUpdate = true;
  colAttr.needsUpdate = true;

  // 3. Animate Relativistic Jets
  if (state.jetsEnabled && state.accretionRate > 0.02) {
    jetSystem.visible = true;
    const jPos = jetSystem.geometry.attributes.position;
    for (let i = 0; i < JET_PARTICLE_COUNT; i++) {
      let y = jPos.getY(i);
      const dir = y >= 0 ? 1 : -1;
      y += dir * delta * (12 + state.spin * 8);

      if (Math.abs(y) > 20) {
        y = dir * (0.2 + Math.random() * 0.5);
      }
      jPos.setY(i, y);
    }
    jetSystem.geometry.attributes.position.needsUpdate = true;
    jetSystem.rotation.y += delta * 0.5;
  } else {
    jetSystem.visible = false;
  }

  // 4. Mode-specific Mesh Visibility
  spacetimeGrid.visible = (state.activeFilter === 'SPACETIME');
  magneticLinesGroup.visible = (state.activeFilter === 'MAGNETIC');

  if (spacetimeGrid.visible) {
    spacetimeGrid.rotation.z += delta * 0.05;
  }
  if (magneticLinesGroup.visible) {
    magneticLinesGroup.rotation.y += delta * (0.2 + state.spin * 0.5);
  }

  // 5. Dynamic Gravitational Lensing Shader Uniform Update
  if (lensingDiskMesh) {
    lensingDiskMesh.material.uniforms.uTime.value = time;
    lensingDiskMesh.material.uniforms.uColorInner.value.setRGB(...mode.innerColor);
    lensingDiskMesh.material.uniforms.uColorOuter.value.setRGB(...mode.outerColor);
    // Orient lensing disk to face camera slightly
    lensingDiskMesh.lookAt(camera.position);
  }

  // 6. Update Controls and Render Scene
  controls.update();
  renderer.render(scene, camera);

  // 7. Update Real-time Telemetry Readouts
  updateTelemetryHUD(rsMeters);
}

// Update HUD Numerical Values
function updateTelemetryHUD(rsMeters) {
  const iscoMeters = calculateISCO(state.mass, state.spin);
  const tempK = calculateTemperature(state.mass, iscoMeters, state.accretionRate);
  const density = calculateDensity(iscoMeters, state.accretionRate, state.mass);
  const pressure = calculatePressure(density, tempK);
  const grav = calculateGravity(state.mass, iscoMeters);
  const velMs = calculateOrbitalVelocity(state.mass, iscoMeters);
  const velFracC = (velMs / C).toFixed(2);

  document.getElementById('hud-rs').innerText = `${(rsMeters / 1000).toFixed(2)} km`;
  document.getElementById('hud-isco').innerText = `${(iscoMeters / 1000).toFixed(2)} km`;
  document.getElementById('hud-temp').innerText = `${formatSci(tempK)} K`;
  document.getElementById('hud-pressure').innerText = `${formatSci(pressure)} Pa`;
  document.getElementById('hud-density').innerText = `${formatSci(density)} kg/m³`;
  document.getElementById('hud-gravity').innerText = `${formatSci(grav)} m/s²`;
  document.getElementById('hud-velocity').innerText = `${velFracC}c`;

  // Time Dilation
  document.getElementById('td-outer').innerText = `${calculateTimeDilation(state.mass, rsMeters * 5).toFixed(2)}x`;
  document.getElementById('td-inner').innerText = `${calculateTimeDilation(state.mass, rsMeters * 2).toFixed(2)}x`;
  document.getElementById('td-horizon').innerText = `${calculateTimeDilation(state.mass, rsMeters * 1.01).toFixed(2)}x`;
}

// Resize Handler
function onWindowResize() {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
}

// ==========================================================================
// 7. UI CONTROLS & EVENT LISTENERS
// ==========================================================================
function setupUI() {
  // Sliders Binding
  bindSlider('input-mass', 'val-mass', ' M☉', (v) => { state.mass = parseFloat(v); });
  bindSlider('input-spin', 'val-spin', '', (v) => { state.spin = parseFloat(v); });
  bindSlider('input-accretion', 'val-accretion', '', (v) => { state.accretionRate = parseFloat(v); });
  bindSlider('input-angle', 'val-angle', '°', (v) => {
    state.viewingAngle = parseFloat(v);
    setCameraAngle(state.viewingAngle);
  });
  bindSlider('input-speed', 'val-speed', 'x', (v) => { state.simSpeed = parseFloat(v); });

  // Toggles Binding
  document.getElementById('toggle-jets').addEventListener('change', (e) => {
    state.jetsEnabled = e.target.checked;
  });
  document.getElementById('toggle-ergosphere').addEventListener('change', (e) => {
    state.ergosphereEnabled = e.target.checked;
  });

  // Black Hole Type Selector
  document.getElementById('select-type').addEventListener('change', (e) => {
    const type = e.target.value;
    if (type === 'stellar') updateMassSlider(10.0);
    else if (type === 'intermediate') updateMassSlider(1000.0);
    else if (type === 'supermassive') updateMassSlider(1000000.0);
  });

  // Presets Selector
  document.getElementById('select-preset').addEventListener('change', (e) => {
    applyPreset(e.target.value);
  });

  // Camera Presets Buttons
  document.querySelectorAll('.btn-preset-cam').forEach(btn => {
    btn.addEventListener('click', () => {
      const mode = btn.getAttribute('data-cam');
      triggerCameraPreset(mode);
    });
  });

  // Filter Bar Buttons
  document.querySelectorAll('.btn-filter').forEach(btn => {
    btn.addEventListener('click', () => {
      setFilterMode(btn.getAttribute('data-filter'));
    });
  });

  // Panel Collapsing
  document.getElementById('toggle-controls').addEventListener('click', () => {
    document.getElementById('panel-controls').classList.toggle('collapsed');
  });
  document.getElementById('toggle-hud').addEventListener('click', () => {
    document.getElementById('panel-hud').classList.toggle('collapsed');
  });

  // Modal Dialogs
  const modal = document.getElementById('modal-about');
  document.getElementById('btn-about').addEventListener('click', () => modal.classList.remove('hidden'));
  document.getElementById('modal-close').addEventListener('click', () => modal.classList.add('hidden'));

  // Reset Button
  document.getElementById('btn-reset').addEventListener('click', resetSimulation);

  // Keyboard Shortcuts
  window.addEventListener('keydown', (e) => {
    if (e.key >= '0' && e.key <= '9') {
      const filterKeys = ['TIMEDILATION', 'NORMAL', 'XRAY', 'TEMPERATURE', 'PRESSURE', 'DENSITY', 'GRAVITY', 'VELOCITY', 'SPACETIME', 'MAGNETIC'];
      setFilterMode(filterKeys[parseInt(e.key)]);
    } else if (e.key.toLowerCase() === 'r') {
      resetSimulation();
    } else if (e.key.toLowerCase() === 'g') {
      triggerCameraPreset('gods');
    } else if (e.key.toLowerCase() === 'j') {
      const toggle = document.getElementById('toggle-jets');
      toggle.checked = !toggle.checked;
      state.jetsEnabled = toggle.checked;
    } else if (e.key.toLowerCase() === 'e') {
      const toggle = document.getElementById('toggle-ergosphere');
      toggle.checked = !toggle.checked;
      state.ergosphereEnabled = toggle.checked;
    }
  });
}

function bindSlider(id, readoutId, suffix, callback) {
  const input = document.getElementById(id);
  const readout = document.getElementById(readoutId);
  input.addEventListener('input', (e) => {
    const val = e.target.value;
    readout.innerText = val + suffix;
    callback(val);
  });
}

function updateMassSlider(val) {
  state.mass = val;
  const slider = document.getElementById('input-mass');
  slider.max = Math.max(100, val).toString();
  slider.value = val;
  document.getElementById('val-mass').innerText = `${val} M☉`;
}

function setFilterMode(modeKey) {
  if (!FILTER_MODES[modeKey]) return;
  state.activeFilter = modeKey;

  // UI Active Button Update
  document.querySelectorAll('.btn-filter').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-filter') === modeKey);
  });

  // HUD Info Box Update
  const modeInfo = FILTER_MODES[modeKey];
  document.getElementById('info-box-title').innerText = modeInfo.title;
  document.getElementById('info-box-desc').innerText = modeInfo.desc;
}

function setCameraAngle(degrees) {
  const rad = (degrees * Math.PI) / 180;
  const dist = camera.position.length();
  camera.position.x = 0;
  camera.position.y = dist * Math.cos(rad);
  camera.position.z = dist * Math.sin(rad);
  camera.lookAt(0, 0, 0);
}

function triggerCameraPreset(preset) {
  state.cameraPreset = preset;
  if (preset === 'orbit') {
    camera.position.set(0, 18, 38);
  } else if (preset === 'top') {
    camera.position.set(0, 45, 0.1);
  } else if (preset === 'side') {
    camera.position.set(45, 0, 0);
  } else if (preset === 'edge') {
    camera.position.set(0, 0.5, 42);
  } else if (preset === 'gods') {
    camera.position.set(22, 35, 22);
  }
  camera.lookAt(0, 0, 0);
}

function applyPreset(presetKey) {
  if (presetKey === 'quiet') {
    updateMassSlider(10);
    state.spin = 0.1;
    state.accretionRate = 0.05;
    state.jetsEnabled = false;
  } else if (presetKey === 'active') {
    updateMassSlider(20);
    state.spin = 0.85;
    state.accretionRate = 0.9;
    state.jetsEnabled = true;
  } else if (presetKey === 'spin') {
    updateMassSlider(15);
    state.spin = 0.998;
    state.accretionRate = 0.5;
    state.ergosphereEnabled = true;
  } else if (presetKey === 'extreme') {
    updateMassSlider(80);
    state.spin = 0.95;
    state.accretionRate = 1.0;
  } else if (presetKey === 'supermassive') {
    updateMassSlider(1000000);
    state.spin = 0.70;
    state.accretionRate = 0.4;
  } else if (presetKey === 'binary') {
    updateMassSlider(14);
    state.spin = 0.65;
    state.accretionRate = 0.8;
    setFilterMode('XRAY');
  } else if (presetKey === 'jet') {
    updateMassSlider(30);
    state.spin = 0.92;
    state.accretionRate = 0.85;
    state.jetsEnabled = true;
  } else if (presetKey === 'educational') {
    updateMassSlider(10);
    state.spin = 0.72;
    state.accretionRate = 0.35;
    setFilterMode('NORMAL');
  }

  // Update UI Inputs
  document.getElementById('input-spin').value = state.spin;
  document.getElementById('val-spin').innerText = state.spin.toFixed(3);
  document.getElementById('input-accretion').value = state.accretionRate;
  document.getElementById('val-accretion').innerText = state.accretionRate.toFixed(2);
  document.getElementById('toggle-jets').checked = state.jetsEnabled;
  document.getElementById('toggle-ergosphere').checked = state.ergosphereEnabled;
}

function resetSimulation() {
  state.mass = 10.0;
  state.spin = 0.720;
  state.accretionRate = 0.35;
  state.viewingAngle = 65;
  state.simSpeed = 1.0;
  state.jetsEnabled = true;
  state.ergosphereEnabled = false;

  updateMassSlider(10.0);
  document.getElementById('input-spin').value = 0.720;
  document.getElementById('val-spin').innerText = '0.720';
  document.getElementById('input-accretion').value = 0.35;
  document.getElementById('val-accretion').innerText = '0.35';
  document.getElementById('input-angle').value = 65;
  document.getElementById('val-angle').innerText = '65°';
  document.getElementById('input-speed').value = 1.0;
  document.getElementById('val-speed').innerText = '1.0x';
  document.getElementById('toggle-jets').checked = true;
  document.getElementById('toggle-ergosphere').checked = false;
  document.getElementById('select-preset').value = 'default';
  document.getElementById('select-type').value = 'stellar';

  setFilterMode('NORMAL');
  triggerCameraPreset('orbit');
}

// ==========================================================================
// 8. INITIALIZATION ENTRY POINT
// ==========================================================================
window.addEventListener('DOMContentLoaded', () => {
  const loadingStatus = document.getElementById('loading-status');

  setTimeout(() => { loadingStatus.innerText = "Loading accretion disk..."; }, 300);
  setTimeout(() => { loadingStatus.innerText = "Loading particle field..."; }, 600);
  setTimeout(() => { loadingStatus.innerText = "Initializing relativistic model..."; }, 900);

  setTimeout(() => {
    const success = initThree();
    if (success) {
      setupUI();
      animate();
      const loader = document.getElementById('loading-screen');
      loader.classList.add('hidden');
    }
  }, 1200);
});
